### ISSUE TITLE
{Plain Text Translation} As a newish programmer, I want to be able to see how my high-level programming logic translates directly into code in order to start developing a fundamental coding understanding.

### ISSUE THREAD

**Issue by RobertConde** [CEN-3031-Group-2b/Sapphire-Project14-2b#10]
**Acceptance Criteria**

- [x] Code can be transformed from block language to multiple different languages without any delay or errors.

**Tasks**

- [x] Find how Blockly displays translated code [4]
- [x] Switch translation type when language is switched [5]
