### ISSUE TITLE
{Python} As a course creator, I want to be able to manage and create block-based assignments that correspond to my curriculum by having flexibility in the languages available and the languages students can see in order to have a tailored teaching experience.

### ISSUE THREAD

**Issue by RobertConde** [CEN-3031-Group-2b/Sapphire-Project14-2b#2]
**Acceptance Criteria**

- [ ] The languages can be selected by a course creator without any errors. Regardless of which language is chosen, the assignments should be displayed the same and can be worked on in the exact same way.

**Tasks**

- [x] Read Blockly Docs (Python-specific) [5]
- [x] View how Blockly is currently implemented [4]
