### ISSUE TITLE
{Language Switch - Backend} As a new programmer, I want my learning experience to be smooth and integrated with my course by having the block IDE/Editor within easy reach in order to aid in my learning.

### ISSUE THREAD

**Issue by RobertConde** [CEN-3031-Group-2b/Sapphire-Project14-2b#3]
**Acceptance Criteria**

- [ ] The workspace should still contain all of the same functionality and there should be no confusion with how the block language is used.
- [ ] No errors should be introduced by dragging blocks within different languages.

**Tasks**

- [ ] Find how to switch language output in Blockly [5]
- [ ] Implement language switch for JS [3]
- [ ] Implement language switch for Python [3]
