### ISSUE TITLE
{Help Page} As a student who wants to study Computer Science, I want a platform that can help me determine what each language that it provides can do and how it can be applied in applications or projects in order to learn more about different languages.

### ISSUE THREAD

**Issue by RobertConde** [CEN-3031-Group-2b/Sapphire-Project14-2b#5]
**Acceptance Criteria**

- [x] The help page can be clicked and displayed without affecting the code that is written and the workspace functionality.

**Tasks**

- [x] Create a button opening a page giving information on the language being used [4]
- [x] Provide links to documentation and information on how to switch languages[3]
- [x] Adjust formatting[2]
