### ISSUE TITLE
{Teacher Options} As a teacher, I want to be able to view all of the projects made by a student in the same portfolio, regardless of which framework is used, in order to make grading and managing assignments easier.

### ISSUE THREAD

**Issue by RobertConde** [CEN-3031-Group-2b/Sapphire-Project14-2b#6]
**Acceptance Criteria**

- [ ] Through a teacher account, two projects made in two different languages can be viewed and interacted with in the same portfolio.

**Tasks**

- [ ] View how teacher privilges are handled [4]
- [ ] Connect backend language switching to permissions [4]
